### PR TITLE
Introduce benevolent version comparator

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by msrb** [comment]
Ideally, this should land in https://github.com/fabric8-analytics/fabric8-analytics-version-comparator in future. If it's useful.

**Comment by msrb** [comment]
Hmm, I am not familiar with the library. So maybe (?) But we are interested in a very special way of comparing versions here. 

```
    Examples:
        BenevolentVersion('1.0.0') == BenevolentVersion('1')  # True
        BenevolentVersion('5.0.RELEASE') == BenevolentVersion('5.0.0')  # True
```

So we don't want to know whether beta version is greater than alpha. This comparator ignores such release strings and considers such versions equal.

**Comment by msrb** [comment]
And the reason for such "benevolent" comparator is the weirdness of NVD, where versions don't always reflect the reality.

**Comment by tisnik** [comment]
I see. Yes in case the SemVer is not followed, let's use Benevolent Class :) IMHO it is a really good candidate for a regular package and for module in our famous fabric8-analytics-comparator.

**Comment by tisnik** [comment]
ah I forgot - LGTM of course ;)

**Pull request merged**
