### PR TITLE
Add support for > and < operators

### PR DESCRIPTION
**Pull request by msrb**
It turned out these are used in NVD as well, and quite often.

### CODE REVIEW

**Comment by msrb** [comment]
[test]

**Comment by tisnik** [comment]
pylint does not like you @msrb  :) I'd just split the test

**Comment by msrb** [comment]
@tisnik hmm, looks like this is about maintainability index (?) Is it possible that the file is simply getting too big?

**Comment by tisnik** [comment]
> @tisnik hmm, looks like this is about maintainability index (?) Is it possible that the file is simply getting too big?

Yes, a bit. Usually if you add several lines of comments, it will help.

**Comment by msrb** [comment]
[test]

**Comment by tisnik** [comment]
[test]

**Pull request merged**
